sReports/sReportsV2/Controllers/SmartOncologyController.cs
using sReportsV2.BusinessLayer.Interfaces;
using sReportsV2.Common.CustomAttributes;
using sReportsV2.Common.Extensions;
using sReportsV2.Cache.Singleton;
using sReportsV2.DTOs.Autocomplete;
using sReportsV2.DTOs.DTOs.SmartOncology.ChemotherapySchema.DataIn;
using sReportsV2.DTOs.DTOs.SmartOncology.ChemotherapySchema.DataOut;
using sReportsV2.DTOs.DTOs.SmartOncology.ChemotherapySchema.DTO;
using sReportsV2.DTOs.DTOs.SmartOncology.ChemotherapySchemaInstance.DataIn;
using sReportsV2.DTOs.DTOs.SmartOncology.Enum.DataIn;
using sReportsV2.DTOs.DTOs.SmartOncology.Enum.DataOut;
using sReportsV2.DTOs.DTOs.SmartOncology.HistorySheet.DataOut;
using sReportsV2.DTOs.Pagination;
using System;
using System.Linq;
using sReportsV2.DTOs.DTOs.SmartOncology.ChemotherapySchemaInstance.DataOut;
using sReportsV2.Common.Constants;
using sReportsV2.Common.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using sReportsV2.DTOs.Patient.DataOut;
using sReportsV2.DTOs.Patient.DataIn;
using sReportsV2.DTOs.Patient;
using sReportsV2.DTOs.Common.DTO;
using AutoMapper;
using sReportsV2.Common.Entities.User;
using System.Threading.Tasks;

namespace sReportsV2.Controllers
{
    public class SmartOncologyController : BaseController
    {
        private readonly IPatientBLL patientBLL;
        private readonly IChemotherapySchemaBLL chemotherapySchemaBLL;
        private readonly IChemotherapySchemaInstanceBLL chemotherapySchemaInstanceBLL;
        private readonly ITrialManagementBLL trialManagementBLL;
        private readonly IMapper mapper;

        public SmartOncologyController(IChemotherapySchemaBLL chemotherapySchemaBLL, 
            IChemotherapySchemaInstanceBLL chemotherapySchemaInstanceBLL, 
            ITrialManagementBLL trialManagementBLL, 
            IHttpContextAccessor httpContextAccessor, 
            IServiceProvider serviceProvider, 
            IConfiguration configuration, 
            IPatientBLL patientBLL,
            IMapper mapper, 
            IAsyncRunner asyncRunner,
            ICacheRefreshService cacheRefreshService) : 
            base(httpContextAccessor, serviceProvider, configuration, asyncRunner, cacheRefreshService)
        {
            this.chemotherapySchemaBLL = chemotherapySchemaBLL;
            this.chemotherapySchemaInstanceBLL = chemotherapySchemaInstanceBLL;
            this.trialManagementBLL = trialManagementBLL;
            this.patientBLL = patientBLL;
            this.mapper = mapper;
        }

        [SReportsAuthorize(Permission = PermissionNames.View, Module = ModuleNames.ClinicalOncology)]
        public ActionResult HistorySheet(int? patientId)
        {
            var patient = patientId != null ? patientBLL.GetById(patientId.Value, loadClinicalTrials: true) : null;
            return View(new HistorySheetDataOut() { Patient = patient });
        }

        [SReportsAuthorize(Permission = PermissionNames.View, Module = ModuleNames.ClinicalOncology)]
        public ActionResult PatientOncologyDiseaseHistory(ChemotherapySchemaInstanceFilterDataIn dataIn)
        {
            dataIn = Ensure.IsNotNull(dataIn, nameof(dataIn));
            var data = patientBLL.GetPreviewById(dataIn.PatientId);
            ViewBag.FilterData = dataIn;
            SetSmartOncologyCodeSetsToViewBag();
            return View("Patient/OncologyDiseasesHistory", data);
        }

        [SReportsAuthorize(Permission = PermissionNames.View, Module = ModuleNames.ClinicalOncology)]
        public async Task<ActionResult> BasicPatientDataOncology(PatientFilterDataIn filterDataIn)
        {
            return await GetPatients(filterDataIn, false).ConfigureAwait(false);
        }

        public async Task<ActionResult> ReloadPatientTable(PatientFilterDataIn filterDataIn)
        {
            return await GetPatients(filterDataIn, true).ConfigureAwait(false);
        }

        public ActionResult CreatePatientData()
        {
            SetFormEnumViewbags();
            SetGenderTypesToViewBag();
            SetSmartOncologyCodeSetsToViewBag();
            return PartialView("Patient/EditPatientData");
        }

        public ActionResult ViewPatientData(int id)
        {
            var data = patientBLL.GetById(id, loadClinicalTrials: true);
            SetGenderTypesToViewBag();
            SetSmartOncologyCodeSetsToViewBag();
            return PartialView("Patient/ViewPatientData", data);
        }

        public ActionResult EditPatientData(int id)
        {
            var data = patientBLL.GetById(id, loadClinicalTrials: true);
            SetFormEnumViewbags();
            SetGenderTypesToViewBag();
            SetSmartOncologyCodeSetsToViewBag();
            return PartialView("Patient/EditPatientData", data);
        }

        [SReportsAuthorize(Permission = PermissionNames.Update, Module = ModuleNames.ClinicalOncology)]
        [HttpPost]
        public ActionResult EditPatientData(PatientDataIn patientDataIn)
        {
            patientDataIn = Ensure.IsNotNull(patientDataIn, nameof(patientDataIn));
            patientDataIn.PatientChemotherapyData.PatientInformedBy = string.Concat(userCookieData.FirstName, " ", userCookieData.LastName);
            ResourceCreatedDTO resourceCreatedDTO = patientBLL.InsertOrUpdate(patientDataIn, mapper.Map<UserData>(userCookieData));

            return Json(resourceCreatedDTO);
        }

        public ActionResult ReloadClinicalTrial(string name)
        {
            var data = trialManagementBLL.GetlClinicalTrialsByName(name);
            return PartialView("Patient/ClinicalTrialValues", data);
        }

        public ActionResult GetAutocompleteEnumData(SmartOncologyEnumAutocompleteDataIn dataIn)
        {
            dataIn = Ensure.IsNotNull(dataIn, nameof(dataIn));

            var filtered = SingletonDataContainer.Instance.GetSmartOncologyEnums(dataIn.EnumType)
                .Where(e => e.Name.ToLower().Contains(dataIn.Term.ToLower()));
            var enumDataOuts = filtered
                .OrderBy(x => x.Name).Skip(dataIn.GetHowManyElementsToSkip()).Take(FilterConstants.DefaultPageSize)
                .Select(e => new AutocompleteDataOut()
                {
                    id = e.Name,
                    text = e.Name
                })
                .Where(x => string.IsNullOrEmpty(dataIn.ExcludeId) || !x.id.Equals(dataIn.ExcludeId))
                .ToList()
                ;

            AutocompleteResultDataOut result = new AutocompleteResultDataOut()
            {
                pagination = new AutocompletePaginatioDataOut()
                {
                    more = dataIn.ShouldLoadMore(filtered.Count()),
                },
                results = enumDataOuts
            };

            return Json(result);
        }

        public ActionResult GetAutocompletePatientData(AutocompleteDataIn dataIn)
        {
            AutocompleteResultDataOut result = patientBLL.GetAutocompletePatientData(dataIn, userCookieData);

            return Json(result);
        }


        public ActionResult GetAutocompleteSchemaData(AutocompleteDataIn dataIn)
        {
            var result = chemotherapySchemaBLL.GetDataForAutocomplete(dataIn);

            return Json(result);
        }

        [SReportsAuthorize(Permission = PermissionNames.Create, Module = ModuleNames.ClinicalOncology)]
        public ActionResult CreateNewSchema()
        {
            return View("SchemaDefinition/EditSchema");
        }

        [SReportsAuthorize(Permission = PermissionNames.Update, Module = ModuleNames.ClinicalOncology)]
        public ActionResult EditSchema(int id)
        {
            var data = chemotherapySchemaBLL.GetById(id);
            return View("SchemaDefinition/EditSchema", data);
        }

        [Authorize]
        [SReportsAuditLog]
        [HttpPost]
        public ActionResult EditSchema(ChemotherapySchemaDataIn chemotherapySchemaDataIn)
        {
            var data = chemotherapySchemaBLL.InsertOrUpdate(chemotherapySchemaDataIn, userCookieData);
            return Json(data);
        }

        [Authorize]
        [SReportsAuditLog]
        [HttpPost]
        public ActionResult UpdateSchemaGeneralProperties(EditGeneralPropertiesDataIn chemotherapySchemaDataIn)
        {
            var data = chemotherapySchemaBLL.UpdateGeneralProperties(chemotherapySchemaDataIn, userCookieData);
            return Json(data);
        }

        [Authorize]
        [SReportsAuditLog]
        [HttpPost]
        public ActionResult UpdateSchemaIndications(EditIndicationsDataIn indicationsDataIn)
        {
            var data = chemotherapySchemaBLL.UpdateIndications(indicationsDataIn, userCookieData);
            return Json(data);
        }

        [Authorize]
        [SReportsAuditLog]
        [HttpPost]
        public ActionResult UpdateSchemaName(EditNameDataIn nameDataIn)
        {
            var data = chemotherapySchemaBLL.UpdateName(nameDataIn, userCookieData);
            return Json(data);
        }

        public ActionResult GetSchemaReference(int id)
        {
            var data = chemotherapySchemaBLL.GetReference(id);
            return PartialView("SchemaDefinition/EditReferenceModal", data);
        }

        [Authorize]
        [SReportsAuditLog]
        [HttpPost]
        public ActionResult UpdateSchemaReference(EditLiteratureReferenceDataIn referenceDataIn)
        {
            var data = chemotherapySchemaBLL.UpdateReference(referenceDataIn, userCookieData);
            return Json(data);
        }

        public ActionResult GetSchemaMedication(int id)
        {
            var data = chemotherapySchemaBLL.GetMedication(id);
            ViewBag.BodyCalculationFormulas = chemotherapySchemaBLL.GetFormulas();
            ViewBag.SchemaDefinitionMedication = true;
            return PartialView("SchemaDefinition/EditMedication", data);
        }

        [Authorize]
        [SReportsAuditLog]

sReports/sReportsV2/Views/SmartOncology/Patient/BasicPatientDataOncology.cshtml
@using sReportsV2.Common.Helpers
@using sReportsV2.DTOs.Patient.DataIn;
@using sReportsV2.DTOs.Patient.DataOut;
@using sReportsV2.Common.Constants;

@* @ScriptHelper.RenderStylesheet(Url.Content("/css/open-oncology/scss/style.css")) *@

@model  sReportsV2.DTOs.Pagination.PaginationDataOut<PatientTableDataOut, PatientFilterDataIn>

@{
    ViewBag.Title = @sReportsV2.Cache.Resources.TextLanguage.Clinical_Oncology_Patient_Management;
    var userCookieData = ViewBag.UserCookieData;
    bool hasCreatePerm = userCookieData.UserHasPermission(PermissionNames.Create, ModuleNames.ClinicalOncology);
}

@await Html.PartialAsync("Breadcrumb", new ViewDataDictionary(ViewData) { { "level1", @sReportsV2.Cache.Resources.TextLanguage.Clinical_Oncology_Patient_Management }, { "activeLevel", 1 } })

<div class="smart-oncology-header">
    <span>@sReportsV2.Cache.Resources.TextLanguage.Clinical_Oncology_Patient_Management</span>
    @if (hasCreatePerm)
    {
        <button class="new-patient float-right" onclick="addNewPatient()">
            @sReportsV2.Cache.Resources.TextLanguage.New_Patient
        </button>
    }
</div>
<div class="smart-oncology-container">
    <div class="smart-oncology-search-container">
        @await Html.PartialAsync("Patient/BasicPatientDataOncologyHeader", Model)
        @await Html.PartialAsync("Patient/BasicPatientDataOncologyHeaderMobile", Model)
        <div class="smart-oncology-patient-detail" id="smart-oncology-patient-detail">
        </div>
    </div>
</div>

@Html.Raw(ScriptHelper.RenderScript(Url.Content("~/js/openOncology/smartOncologyPatient.js"), "", ""))

<script>
    var defaultFilter = @Html.Raw(Json.Serialize(Model.DataIn));
    setInitialViewData(defaultFilter.SelectedPatientId);
</script>

sReports/sReportsV2/Views/SmartOncology/Patient/BasicPatientDataOncologyHeaderMobile.cshtml
@using sReportsV2.DTOs.Patient.DataIn;
@using sReportsV2.DTOs.Patient.DataOut;
@model  sReportsV2.DTOs.Pagination.PaginationDataOut<PatientTableDataOut, PatientFilterDataIn>

<div class="visible-md">
    <header class="header header-patient">
        <div class="search-container-mobile">
            <input name="patientSearchName" class="w-100 patientSearchName" type="text" placeholder="@sReportsV2.Cache.Resources.TextLanguage.Search_patient_placeholder" />
            <img alt="" class="search-i" id="searchPatientNameIcon" src="/css/img/icons/search_green.svg" onclick="searchTable(event)">
            <img alt="" class="close-i" id="closePatientNameIcon" src="/css/img/icons/close_black.svg">
        </div>
    </header>
    <div class="smartOncologyPatientEntries">
        @await Html.PartialAsync("Patient/PatientEntriesTable", Model)
    </div>
    <div class="divider"></div>
</div>

sReports/sReportsV2/Views/SmartOncology/Patient/OncologyDiseasesHistory.cshtml
@using System.Globalization
@using sReportsV2.Common.Helpers;
@using sReportsV2.Common.Extensions;
@using sReportsV2.DTOs.Patient.DataOut;
@model PatientTableDataOut

@{
    ViewBag.Title = sReportsV2.Cache.Resources.TextLanguage.History_of_Oncological_Disease;
    string patientName = string.Concat(Model.FirstName, " ", Model.LastName);
}

@await Html.PartialAsync("Breadcrumb", new ViewDataDictionary(ViewData) { { "level1", @sReportsV2.Cache.Resources.TextLanguage.Clinical_Oncology_Patient_Management }, { "linkLevel1", "/SmartOncology/BasicPatientDataOncology" }, { "level2", @sReportsV2.Cache.Resources.TextLanguage.History_of_Oncological_Disease }, { "linkLevel2", "/SmartOncology/BasicPatientDataOncology?selectedPatientId=" + Model.Id }, { "level3", patientName }, { "activeLevel", 3 } })

<div class="table-container border-0">
    <div class="header header-new">
        @sReportsV2.Cache.Resources.TextLanguage.History_of_Oncological_Disease (@patientName@(Model.BirthDate != null ? ", " + Model.BirthDate.Value.GetDateTimeDisplay(ViewBag.DateFormat as string, excludeTimePart: true) : ""))
        <button class="btn btn-create float-right" onclick="newEntity()"><i class="fas fa-plus-circle"></i> @sReportsV2.Cache.Resources.TextLanguage.Create</button>
    </div>

    @await Html.PartialAsync("SchemaInstance/SchemaInstanceFilterGroup")

    <div id="tableContainer">
    </div>
</div>

@await Html.PartialAsync("SchemaInstance/AdvancedFilterModal")

<script>
    var defaultFilter = @Html.Raw(Json.Serialize(ViewBag.FilterData));
</script>

@Html.Raw(ScriptHelper.RenderScript(Url.Content("~/js/sReports/common/tableCommon.js"), "", ""))
@Html.Raw(ScriptHelper.RenderScript(Url.Content("~/js/openOncology/smartOncologyPatientDiseasesHistory.js"), "", ""))

sReports/sReportsV2/Views/SmartOncology/Patient/ViewPatientData.cshtml
@using System.Globalization
@using sReportsV2.Common.Enums;
@using sReportsV2.DTOs.CodeEntry.DataOut;
@using sReportsV2.Common.Constants;
@using sReportsV2.DTOs.Patient;
@using sReportsV2.DTOs.DTOs.Patient.DataOut;
@using sReportsV2.Cache.Extensions;
@using sReportsV2.Common.Extensions;
@model PatientDataOut

@{
    var userCookieData = ViewBag.UserCookieData;
    PatientChemotherapyDataDataOut patientChemotherapyData = Model != null && Model.PatientChemotherapyData != null ? Model.PatientChemotherapyData : new PatientChemotherapyDataDataOut();
    string activeLanguage = userCookieData.ActiveLanguage;
    List<CodeDataOut> genders = ViewBag.Genders as List<CodeDataOut>;
    CodeDataOut genderEnum = genders.Find(g => g.Id == Model.GenderId);
    string genderTranslated = genderEnum != null ? genderEnum.Thesaurus.GetPreferredTermByTranslationOrDefault(activeLanguage) : string.Empty;
    bool hasUpdatePerm = userCookieData.UserHasPermission(PermissionNames.Update, ModuleNames.ClinicalOncology);
    List<CodeDataOut> contraceptions = ViewBag.Contraceptions as List<CodeDataOut>;
    List<CodeDataOut> diseaseContexts = ViewBag.DiseaseContexts as List<CodeDataOut>;
}

<div class="smart-oncology-patient-detail-header">
    <div class="row">
        <div class="col">
            <span class="smart-oncology-patient-detail-title">@sReportsV2.Cache.Resources.TextLanguage.Clinical_Oncology_Patient_Management</span>
        </div>
        <div class="col">
            <span class="smart-oncology-patient-detail-title ml-2 hidden-md">@sReportsV2.Cache.Resources.TextLanguage.History_of_Oncological_Disease</span>
            @if (hasUpdatePerm)
            {
                <span class="smart-oncology-patient-edit-btn" onclick="editPatient('@Model.Id')">
                    <img alt="" src="/css/img/icons/edit_pencil_02.svg">
                    <span class="pl-2 btn-label">@sReportsV2.Cache.Resources.TextLanguage.Edit</span>
                </span>
            }
        </div>
    </div>
</div>
<div class="smart-oncology-patient-detail-container">
    <div class="row ml-0">
        <div class="col-12 col-lg mr-lg-2">
            <text>
                @{
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.FirstName, Model.Name);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.SecondName, Model.FamilyName);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Gender, genderTranslated);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Date_of_birth, Model.BirthDate.GetDateTimeDisplay(ViewBag.DateFormat as string, excludeTimePart: true));
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Identification_number, patientChemotherapyData.IdentificationNumber);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Allergies, patientChemotherapyData.Allergies != null ? patientChemotherapyData.Allergies.Replace(";", ", ") : "");
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Patient_is_informed_for, patientChemotherapyData.PatientInformedFor);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Patient_Informed_by, patientChemotherapyData.PatientInformedBy);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Patient_info_signed_on, patientChemotherapyData.PatientInfoSignedOn.GetDateTimeDisplay(ViewBag.DateFormat as string, excludeTimePart: true));
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Copy_delivered_on, patientChemotherapyData.CopyDeliveredOn.GetDateTimeDisplay(ViewBag.DateFormat as string, excludeTimePart: true));
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Capability_to_work, string.Concat(patientChemotherapyData.CapabilityToWork, " ", "%"));
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Desire_to_have_children, patientChemotherapyData.DesireToHaveChildren ? sReportsV2.Cache.Resources.TextLanguage.Yes : sReportsV2.Cache.Resources.TextLanguage.No_);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Fertility_conservation, patientChemotherapyData.FertilityConservation ? sReportsV2.Cache.Resources.TextLanguage.Yes : sReportsV2.Cache.Resources.TextLanguage.No_);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Semen_cryopreservation, patientChemotherapyData.SemenCryopreservation ? sReportsV2.Cache.Resources.TextLanguage.Yes : sReportsV2.Cache.Resources.TextLanguage.No_, Model.GenderName == Gender.Male.ToString());
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Egg_cell_cryopreservation, patientChemotherapyData.EggCellCryopreservation ? sReportsV2.Cache.Resources.TextLanguage.Yes : sReportsV2.Cache.Resources.TextLanguage.No_, Model.GenderName == Gender.Female.ToString());
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Sexual_health_addressed, patientChemotherapyData.SexualHealthAddressed ? sReportsV2.Cache.Resources.TextLanguage.Yes : sReportsV2.Cache.Resources.TextLanguage.No_);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Copy_delivered_on, patientChemotherapyData.CopyDeliveredOn.GetDateTimeDisplay(ViewBag.DateFormat as string, excludeTimePart: true));
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Contraception, @patientChemotherapyData.ConvertContraceptionCDToDisplayName(contraceptions, activeLanguage));
                    @*RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Clinical_trials, Model.ClinicalTrials != null ? string.Join(", ", Model.ClinicalTrials.Select(x => x.Name)) : "")*@
                }
            </text>
        </div>
        <div class="col-12 col-lg ml-lg-2 mt-3 mt-lg-0">
            <div class="margin-bottom-15 visible-md">
                <div class="row">
                    <span class="smart-oncology-patient-detail-title">@sReportsV2.Cache.Resources.TextLanguage.History_of_Oncological_Disease</span>
                </div>
            </div>
            <text>
                @{
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Previous_Treatment, patientChemotherapyData.PreviousTreatment ? sReportsV2.Cache.Resources.TextLanguage.Yes : sReportsV2.Cache.Resources.TextLanguage.No_);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Treatment_in_Graubunden, patientChemotherapyData.TreatmentInCantonalHospitalGraubunden ? sReportsV2.Cache.Resources.TextLanguage.Yes : sReportsV2.Cache.Resources.TextLanguage.No_, patientChemotherapyData.PreviousTreatment);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.History_of_Oncological_Disease, Html.ActionLink(sReportsV2.Cache.Resources.TextLanguage.Link, "PatientOncologyDiseaseHistory", "SmartOncology", new { patientId = Model.Id }, new { target = "_blank", rel = "noreferrer", @class = "advanced-link" }), patientChemotherapyData.PreviousTreatment && patientChemotherapyData.TreatmentInCantonalHospitalGraubunden);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Hospital_praxis_of_previous_treatment, patientChemotherapyData.HospitalOrPraxisOfPreviousTreatments != null ? patientChemotherapyData.HospitalOrPraxisOfPreviousTreatments.Replace(";", ", ") : "", patientChemotherapyData.PreviousTreatment && !patientChemotherapyData.TreatmentInCantonalHospitalGraubunden);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Disease_context_at_initial_presentation, !patientChemotherapyData.DiseaseContextAtInitialPresentationCD.HasValue ? "" : @patientChemotherapyData.ConvertDiseaseContextAtInitialPresentationCDToDisplayName(diseaseContexts, activeLanguage), patientChemotherapyData.PreviousTreatment && !patientChemotherapyData.TreatmentInCantonalHospitalGraubunden);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Stage_at_initial_presentation, patientChemotherapyData.StageAtInitialPresentation, patientChemotherapyData.PreviousTreatment);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Disease_context_at_current_presentation, !patientChemotherapyData.DiseaseContextAtCurrentPresentationCD.HasValue ? "" : @patientChemotherapyData.ConvertDiseaseContextAtCurrentPresentationCDToDisplayName(diseaseContexts, activeLanguage));
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Stage_at_current_presentation, patientChemotherapyData.StageAtCurrentPresentation);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Anatomy, patientChemotherapyData.Anatomy);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Morphology, patientChemotherapyData.Morphology);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Therapeutic_context, patientChemotherapyData.TherapeuticContext);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Chemotherapy_Type, patientChemotherapyData.ChemotherapyType);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Chemotherapy_Course, patientChemotherapyData.ChemotherapyCourse);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Chemotherapy_Cycle, patientChemotherapyData.ChemotherapyCycle);
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.First_Day_of_Chemotherapy, patientChemotherapyData.FirstDayOfChemotherapy.GetDateTimeDisplay(ViewBag.DateFormat as string, excludeTimePart: true));
                    RenderPatientCellData(sReportsV2.Cache.Resources.TextLanguage.Consecutive_chemotherapy_days, patientChemotherapyData.ConsecutiveChemotherapyDays.HasValue ? patientChemotherapyData.ConsecutiveChemotherapyDays.Value : 1);
                }
            </text>
        </div>
    </div>
</div>

@functions {
    private void RenderPatientCellData(string name, object value, bool condition = true)
    {
        if (condition)
        {
            <div class="row pl-0">
                <div class="col-5 column data-name">@name:</div>
                <div class="col-7 column">
                    <div class="input">
                        <div>
                            @value
                        </div>
                    </div>
                </div>
            </div>
        }
    }
}